Vagrant.configure("2") do |c|
  c.vm.define 'centos-65-x64' do |v|
    v.vm.hostname = 'centos-65-x64'
    v.vm.box = 'puppetlabs/centos-6.5-64-nocm'
    v.vm.box_url = 'https://vagrantcloud.com/puppetlabs/boxes/centos-6.5-64-nocm'
    v.vm.box_check_update = 'true'
    v.vm.network :private_network, ip: "10.255.180.196", :netmask => "255.255.0.0", :mac => "0800279744B7"
    v.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
    end
  end
end
